name: merge-main-into-small-image.yml
on:
  pull_request:
    branches:
      - main   
    types:
      - closed
jobs:
  merge-main-into-small-image:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    timeout-minutes: 3
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Merge with main
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout small-image
        git merge main --no-ff --no-edit
        git push origin small-image
